system:
  Darwin

app_bindings:
  browser: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
  editor: "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
  terminal: "/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal"
  default_applications:
    pdf_viewer: "/System/Applications/Preview.app/Contents/MacOS/Preview"
    media_player: "/Applications/VLC.app/Contents/MacOS/VLC"

system_information: "AUTO_POPULATE"

logging:
  file: "/Users/<USERNAME>/AITaskforce/logs/assistant.log"
